//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.eServices.Mvc.DataAccessLayer.eBilling6Months
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eBilling6Months : DbContext
    {
        public eBilling6Months()
            : base("name=eBilling6Months")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<QueueArchive> QueueArchives { get; set; }
        public virtual DbSet<QueuePending> QueuePendings { get; set; }
        public virtual DbSet<SystemError> SystemErrors { get; set; }
        public virtual DbSet<BillsArchive> BillsArchives { get; set; }
    
        public virtual ObjectResult<pr_REPORT_BillingHistorySummary_Result> pr_REPORT_BillingHistorySummary(Nullable<decimal> accountNumber)
        {
            var accountNumberParameter = accountNumber.HasValue ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_REPORT_BillingHistorySummary_Result>("pr_REPORT_BillingHistorySummary", accountNumberParameter);
        }
    
        public virtual ObjectResult<pr_REPORT_BillingHistory_Result> pr_REPORT_BillingHistory(Nullable<decimal> accountNumber)
        {
            var accountNumberParameter = accountNumber.HasValue ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_REPORT_BillingHistory_Result>("pr_REPORT_BillingHistory", accountNumberParameter);
        }
    
        public virtual ObjectResult<pr_REPORT_BillingHistoryDetails_Result> pr_REPORT_BillingHistoryDetails(Nullable<decimal> accountNumber, Nullable<System.DateTime> billDate)
        {
            var accountNumberParameter = accountNumber.HasValue ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(decimal));
    
            var billDateParameter = billDate.HasValue ?
                new ObjectParameter("BillDate", billDate) :
                new ObjectParameter("BillDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_REPORT_BillingHistoryDetails_Result>("pr_REPORT_BillingHistoryDetails", accountNumberParameter, billDateParameter);
        }
    
        public virtual ObjectResult<pr_SCRIPT_RequeueBill_Result> pr_SCRIPT_RequeueBill(Nullable<decimal> accountNumber, Nullable<System.DateTime> billDate)
        {
            var accountNumberParameter = accountNumber.HasValue ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(decimal));
    
            var billDateParameter = billDate.HasValue ?
                new ObjectParameter("BillDate", billDate) :
                new ObjectParameter("BillDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SCRIPT_RequeueBill_Result>("pr_SCRIPT_RequeueBill", accountNumberParameter, billDateParameter);
        }
    }
}
