// <auto-generated />
namespace C8.eServices.Mvc.MigrationsWayleave
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addaudijtta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addaudijtta));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071142330_addaudijtta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
