// <auto-generated />
namespace C8.eServices.Mvc.MigrationsWayleave
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingdeclarationtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdeclarationtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106200208246_addingdeclarationtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
