//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.eServices.Mvc.CorrespondenceSoapService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class Error_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class Status_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMsg {
            get {
                return this.statusMsgField;
            }
            set {
                this.statusMsgField = value;
                this.RaisePropertyChanged("StatusMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1474018577615", ConfigurationName="CorrespondenceSoapService.PortType")]
    public interface PortType {
        
        // CODEGEN: Generating message contract since the operation CaseStart_OfflineForm_Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/Services/WSDL-service0.serviceagent/PortTypeEndpoint0/CaseStart_OfflineForm_Oper" +
            "ation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C8.eServices.Mvc.CorrespondenceSoapService.Error_T), Action="/Services/WSDL-service0.serviceagent/PortTypeEndpoint0/CaseStart_OfflineForm_Oper" +
            "ation", Name="Error", Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
            "/Schema.xsd2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse CaseStart_OfflineForm_Operation(C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/Services/WSDL-service0.serviceagent/PortTypeEndpoint0/CaseStart_OfflineForm_Oper" +
            "ation", ReplyAction="*")]
        System.Threading.Tasks.Task<C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse> CaseStart_OfflineForm_OperationAsync(C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class CaseStartOffline_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CASE_DETAIL cASE_DETAILField;
        
        private SERVICE_DETAILS sERVICE_DETAILSField;
        
        private SERVICE_ADDRESS_DETAILS sERVICE_ADDRESS_DETAILSField;
        
        private WRITER_DETAILS wRITER_DETAILSField;
        
        private WRITER_ADDRESS_DETAILS wRITER_ADDRESS_DETAILSField;
        
        private CUSTOMER_DETAILS cUSTOMER_DETAILSField;
        
        private CUSTOMER_ADDRESS_DETAILS cUSTOMER_ADDRESS_DETAILSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CASE_DETAIL CASE_DETAIL {
            get {
                return this.cASE_DETAILField;
            }
            set {
                this.cASE_DETAILField = value;
                this.RaisePropertyChanged("CASE_DETAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SERVICE_DETAILS SERVICE_DETAILS {
            get {
                return this.sERVICE_DETAILSField;
            }
            set {
                this.sERVICE_DETAILSField = value;
                this.RaisePropertyChanged("SERVICE_DETAILS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SERVICE_ADDRESS_DETAILS SERVICE_ADDRESS_DETAILS {
            get {
                return this.sERVICE_ADDRESS_DETAILSField;
            }
            set {
                this.sERVICE_ADDRESS_DETAILSField = value;
                this.RaisePropertyChanged("SERVICE_ADDRESS_DETAILS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public WRITER_DETAILS WRITER_DETAILS {
            get {
                return this.wRITER_DETAILSField;
            }
            set {
                this.wRITER_DETAILSField = value;
                this.RaisePropertyChanged("WRITER_DETAILS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public WRITER_ADDRESS_DETAILS WRITER_ADDRESS_DETAILS {
            get {
                return this.wRITER_ADDRESS_DETAILSField;
            }
            set {
                this.wRITER_ADDRESS_DETAILSField = value;
                this.RaisePropertyChanged("WRITER_ADDRESS_DETAILS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CUSTOMER_DETAILS CUSTOMER_DETAILS {
            get {
                return this.cUSTOMER_DETAILSField;
            }
            set {
                this.cUSTOMER_DETAILSField = value;
                this.RaisePropertyChanged("CUSTOMER_DETAILS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public CUSTOMER_ADDRESS_DETAILS CUSTOMER_ADDRESS_DETAILS {
            get {
                return this.cUSTOMER_ADDRESS_DETAILSField;
            }
            set {
                this.cUSTOMER_ADDRESS_DETAILSField = value;
                this.RaisePropertyChanged("CUSTOMER_ADDRESS_DETAILS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class CASE_DETAIL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string mainStatusField;
        
        private string currentStatusField;
        
        private string caseCloseDateField;
        
        private string caseOpenDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("ReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MainStatus {
            get {
                return this.mainStatusField;
            }
            set {
                this.mainStatusField = value;
                this.RaisePropertyChanged("MainStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CurrentStatus {
            get {
                return this.currentStatusField;
            }
            set {
                this.currentStatusField = value;
                this.RaisePropertyChanged("CurrentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CaseCloseDate {
            get {
                return this.caseCloseDateField;
            }
            set {
                this.caseCloseDateField = value;
                this.RaisePropertyChanged("CaseCloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CaseOpenDate {
            get {
                return this.caseOpenDateField;
            }
            set {
                this.caseOpenDateField = value;
                this.RaisePropertyChanged("CaseOpenDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class SERVICE_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceTypeField;
        
        private string categoryField;
        
        private string subCategoryField;
        
        private string serviceDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sub-Category", Order=2)]
        public string SubCategory {
            get {
                return this.subCategoryField;
            }
            set {
                this.subCategoryField = value;
                this.RaisePropertyChanged("SubCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceDescription {
            get {
                return this.serviceDescriptionField;
            }
            set {
                this.serviceDescriptionField = value;
                this.RaisePropertyChanged("ServiceDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class SERVICE_ADDRESS_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SameAsCustomer sameAsCustomerField;
        
        private string unitNoField;
        
        private string floorNoField;
        
        private string sectionNoField;
        
        private string buildingComplexField;
        
        private string streetNoField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string suburbDistrictField;
        
        private string cityTownField;
        
        private string streetCodeField;
        
        private string xCoordinatesField;
        
        private string yCoordinatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SameAsCustomer SameAsCustomer {
            get {
                return this.sameAsCustomerField;
            }
            set {
                this.sameAsCustomerField = value;
                this.RaisePropertyChanged("SameAsCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
                this.RaisePropertyChanged("UnitNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("SectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BuildingComplex {
            get {
                return this.buildingComplexField;
            }
            set {
                this.buildingComplexField = value;
                this.RaisePropertyChanged("BuildingComplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SuburbDistrict {
            get {
                return this.suburbDistrictField;
            }
            set {
                this.suburbDistrictField = value;
                this.RaisePropertyChanged("SuburbDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CityTown {
            get {
                return this.cityTownField;
            }
            set {
                this.cityTownField = value;
                this.RaisePropertyChanged("CityTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("X-Coordinates", Order=11)]
        public string XCoordinates {
            get {
                return this.xCoordinatesField;
            }
            set {
                this.xCoordinatesField = value;
                this.RaisePropertyChanged("XCoordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Y-Coordinates", Order=12)]
        public string YCoordinates {
            get {
                return this.yCoordinatesField;
            }
            set {
                this.yCoordinatesField = value;
                this.RaisePropertyChanged("YCoordinates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class SameAsCustomer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool yesField;
        
        private bool yesFieldSpecified;
        
        private bool noField;
        
        private bool noFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Yes {
            get {
                return this.yesField;
            }
            set {
                this.yesField = value;
                this.RaisePropertyChanged("Yes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YesSpecified {
            get {
                return this.yesFieldSpecified;
            }
            set {
                this.yesFieldSpecified = value;
                this.RaisePropertyChanged("YesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified {
            get {
                return this.noFieldSpecified;
            }
            set {
                this.noFieldSpecified = value;
                this.RaisePropertyChanged("NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class WRITER_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Anonymous anonymousField;
        
        private string titleField;
        
        private string surnameField;
        
        private string nameField;
        
        private string iDNoField;
        
        private string telHomeNoField;
        
        private string telWorkNoField;
        
        private string cellNoField;
        
        private string faxNoField;
        
        private string emailAddressField;
        
        private string relationToCustomerField;
        
        private string statusNotificationField;
        
        private string correspondenceNotificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Anonymous Anonymous {
            get {
                return this.anonymousField;
            }
            set {
                this.anonymousField = value;
                this.RaisePropertyChanged("Anonymous");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IDNo {
            get {
                return this.iDNoField;
            }
            set {
                this.iDNoField = value;
                this.RaisePropertyChanged("IDNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TelHomeNo {
            get {
                return this.telHomeNoField;
            }
            set {
                this.telHomeNoField = value;
                this.RaisePropertyChanged("TelHomeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TelWorkNo {
            get {
                return this.telWorkNoField;
            }
            set {
                this.telWorkNoField = value;
                this.RaisePropertyChanged("TelWorkNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CellNo {
            get {
                return this.cellNoField;
            }
            set {
                this.cellNoField = value;
                this.RaisePropertyChanged("CellNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FaxNo {
            get {
                return this.faxNoField;
            }
            set {
                this.faxNoField = value;
                this.RaisePropertyChanged("FaxNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RelationToCustomer {
            get {
                return this.relationToCustomerField;
            }
            set {
                this.relationToCustomerField = value;
                this.RaisePropertyChanged("RelationToCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string StatusNotification {
            get {
                return this.statusNotificationField;
            }
            set {
                this.statusNotificationField = value;
                this.RaisePropertyChanged("StatusNotification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CorrespondenceNotification {
            get {
                return this.correspondenceNotificationField;
            }
            set {
                this.correspondenceNotificationField = value;
                this.RaisePropertyChanged("CorrespondenceNotification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class Anonymous : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool yesField;
        
        private bool yesFieldSpecified;
        
        private bool noField;
        
        private bool noFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Yes {
            get {
                return this.yesField;
            }
            set {
                this.yesField = value;
                this.RaisePropertyChanged("Yes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YesSpecified {
            get {
                return this.yesFieldSpecified;
            }
            set {
                this.yesFieldSpecified = value;
                this.RaisePropertyChanged("YesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified {
            get {
                return this.noFieldSpecified;
            }
            set {
                this.noFieldSpecified = value;
                this.RaisePropertyChanged("NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class WRITER_ADDRESS_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitNoField;
        
        private string floorNoField;
        
        private string sectionNoField;
        
        private string buildingComplexField;
        
        private string streetNoField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string suburbDistrictField;
        
        private string cityTownField;
        
        private string streetCodeField;
        
        private string xCoordinatesField;
        
        private string yCoordinatesField;
        
        private Writer_PostSameAsPhysical writer_PostSameAsPhysicalField;
        
        private WRITER_POSTAL wRITER_POSTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
                this.RaisePropertyChanged("UnitNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("SectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuildingComplex {
            get {
                return this.buildingComplexField;
            }
            set {
                this.buildingComplexField = value;
                this.RaisePropertyChanged("BuildingComplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SuburbDistrict {
            get {
                return this.suburbDistrictField;
            }
            set {
                this.suburbDistrictField = value;
                this.RaisePropertyChanged("SuburbDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CityTown {
            get {
                return this.cityTownField;
            }
            set {
                this.cityTownField = value;
                this.RaisePropertyChanged("CityTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("X-Coordinates", Order=10)]
        public string XCoordinates {
            get {
                return this.xCoordinatesField;
            }
            set {
                this.xCoordinatesField = value;
                this.RaisePropertyChanged("XCoordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Y-Coordinates", Order=11)]
        public string YCoordinates {
            get {
                return this.yCoordinatesField;
            }
            set {
                this.yCoordinatesField = value;
                this.RaisePropertyChanged("YCoordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Writer_PostSameAsPhysical Writer_PostSameAsPhysical {
            get {
                return this.writer_PostSameAsPhysicalField;
            }
            set {
                this.writer_PostSameAsPhysicalField = value;
                this.RaisePropertyChanged("Writer_PostSameAsPhysical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public WRITER_POSTAL WRITER_POSTAL {
            get {
                return this.wRITER_POSTALField;
            }
            set {
                this.wRITER_POSTALField = value;
                this.RaisePropertyChanged("WRITER_POSTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class Writer_PostSameAsPhysical : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool yesField;
        
        private bool yesFieldSpecified;
        
        private bool noField;
        
        private bool noFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Yes {
            get {
                return this.yesField;
            }
            set {
                this.yesField = value;
                this.RaisePropertyChanged("Yes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YesSpecified {
            get {
                return this.yesFieldSpecified;
            }
            set {
                this.yesFieldSpecified = value;
                this.RaisePropertyChanged("YesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified {
            get {
                return this.noFieldSpecified;
            }
            set {
                this.noFieldSpecified = value;
                this.RaisePropertyChanged("NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class WRITER_POSTAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string postalBoxField;
        
        private string suburbDistrictField;
        
        private string cityTownField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PostalBox {
            get {
                return this.postalBoxField;
            }
            set {
                this.postalBoxField = value;
                this.RaisePropertyChanged("PostalBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SuburbDistrict {
            get {
                return this.suburbDistrictField;
            }
            set {
                this.suburbDistrictField = value;
                this.RaisePropertyChanged("SuburbDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CityTown {
            get {
                return this.cityTownField;
            }
            set {
                this.cityTownField = value;
                this.RaisePropertyChanged("CityTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class CUSTOMER_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NewOrExistingCustomer newOrExistingCustomerField;
        
        private string typeField;
        
        private string titleField;
        
        private string nameField;
        
        private string surnameField;
        
        private string iDNoField;
        
        private string accountNumberField;
        
        private string ratesNumberField;
        
        private string connectionNumberField;
        
        private string passportNumberField;
        
        private string telWorkNumberField;
        
        private string cellphoneNoField;
        
        private string telHomeNumberField;
        
        private string faxNumberField;
        
        private string emailAddressField;
        
        private string businessNameField;
        
        private string registrationNumberField;
        
        private string erfNoField;
        
        private string wardNoField;
        
        private string councillorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NewOrExistingCustomer NewOrExistingCustomer {
            get {
                return this.newOrExistingCustomerField;
            }
            set {
                this.newOrExistingCustomerField = value;
                this.RaisePropertyChanged("NewOrExistingCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IDNo {
            get {
                return this.iDNoField;
            }
            set {
                this.iDNoField = value;
                this.RaisePropertyChanged("IDNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RatesNumber {
            get {
                return this.ratesNumberField;
            }
            set {
                this.ratesNumberField = value;
                this.RaisePropertyChanged("RatesNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ConnectionNumber {
            get {
                return this.connectionNumberField;
            }
            set {
                this.connectionNumberField = value;
                this.RaisePropertyChanged("ConnectionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
                this.RaisePropertyChanged("PassportNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TelWorkNumber {
            get {
                return this.telWorkNumberField;
            }
            set {
                this.telWorkNumberField = value;
                this.RaisePropertyChanged("TelWorkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CellphoneNo {
            get {
                return this.cellphoneNoField;
            }
            set {
                this.cellphoneNoField = value;
                this.RaisePropertyChanged("CellphoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TelHomeNumber {
            get {
                return this.telHomeNumberField;
            }
            set {
                this.telHomeNumberField = value;
                this.RaisePropertyChanged("TelHomeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BusinessName {
            get {
                return this.businessNameField;
            }
            set {
                this.businessNameField = value;
                this.RaisePropertyChanged("BusinessName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
                this.RaisePropertyChanged("RegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ErfNo {
            get {
                return this.erfNoField;
            }
            set {
                this.erfNoField = value;
                this.RaisePropertyChanged("ErfNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WardNo {
            get {
                return this.wardNoField;
            }
            set {
                this.wardNoField = value;
                this.RaisePropertyChanged("WardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Councillor {
            get {
                return this.councillorField;
            }
            set {
                this.councillorField = value;
                this.RaisePropertyChanged("Councillor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class NewOrExistingCustomer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool yesField;
        
        private bool yesFieldSpecified;
        
        private bool noField;
        
        private bool noFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Yes {
            get {
                return this.yesField;
            }
            set {
                this.yesField = value;
                this.RaisePropertyChanged("Yes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YesSpecified {
            get {
                return this.yesFieldSpecified;
            }
            set {
                this.yesFieldSpecified = value;
                this.RaisePropertyChanged("YesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified {
            get {
                return this.noFieldSpecified;
            }
            set {
                this.noFieldSpecified = value;
                this.RaisePropertyChanged("NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class CUSTOMER_ADDRESS_DETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitNoField;
        
        private string floorNoField;
        
        private string sectionNoField;
        
        private string buildingComplexField;
        
        private string streetNoField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string suburbDistrictField;
        
        private string cityTownField;
        
        private string streetCodeField;
        
        private string xCoordinatesField;
        
        private string yCoordinatesField;
        
        private SameAsPhysical sameAsPhysicalField;
        
        private Post postField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
                this.RaisePropertyChanged("UnitNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("SectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuildingComplex {
            get {
                return this.buildingComplexField;
            }
            set {
                this.buildingComplexField = value;
                this.RaisePropertyChanged("BuildingComplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SuburbDistrict {
            get {
                return this.suburbDistrictField;
            }
            set {
                this.suburbDistrictField = value;
                this.RaisePropertyChanged("SuburbDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CityTown {
            get {
                return this.cityTownField;
            }
            set {
                this.cityTownField = value;
                this.RaisePropertyChanged("CityTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("X-Coordinates", Order=10)]
        public string XCoordinates {
            get {
                return this.xCoordinatesField;
            }
            set {
                this.xCoordinatesField = value;
                this.RaisePropertyChanged("XCoordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Y-Coordinates", Order=11)]
        public string YCoordinates {
            get {
                return this.yCoordinatesField;
            }
            set {
                this.yCoordinatesField = value;
                this.RaisePropertyChanged("YCoordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public SameAsPhysical SameAsPhysical {
            get {
                return this.sameAsPhysicalField;
            }
            set {
                this.sameAsPhysicalField = value;
                this.RaisePropertyChanged("SameAsPhysical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Post Post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
                this.RaisePropertyChanged("Post");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class SameAsPhysical : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool yesField;
        
        private bool yesFieldSpecified;
        
        private bool noField;
        
        private bool noFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Yes {
            get {
                return this.yesField;
            }
            set {
                this.yesField = value;
                this.RaisePropertyChanged("Yes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YesSpecified {
            get {
                return this.yesFieldSpecified;
            }
            set {
                this.yesFieldSpecified = value;
                this.RaisePropertyChanged("YesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoSpecified {
            get {
                return this.noFieldSpecified;
            }
            set {
                this.noFieldSpecified = value;
                this.RaisePropertyChanged("NoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class Post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string unitNoField;
        
        private string floorNoField;
        
        private string sectionNoField;
        
        private string buildingComplexField;
        
        private string postalBoxField;
        
        private string streetNoField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string suburbDistrictField;
        
        private string cityTownField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
                this.RaisePropertyChanged("UnitNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("SectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuildingComplex {
            get {
                return this.buildingComplexField;
            }
            set {
                this.buildingComplexField = value;
                this.RaisePropertyChanged("BuildingComplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostalBox {
            get {
                return this.postalBoxField;
            }
            set {
                this.postalBoxField = value;
                this.RaisePropertyChanged("PostalBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SuburbDistrict {
            get {
                return this.suburbDistrictField;
            }
            set {
                this.suburbDistrictField = value;
                this.RaisePropertyChanged("SuburbDistrict");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CityTown {
            get {
                return this.cityTownField;
            }
            set {
                this.cityTownField = value;
                this.RaisePropertyChanged("CityTown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
        "/Schema.xsd2")]
    public partial class CaseStartOffline_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNoField;
        
        private Status_T statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReferenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("ReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Status_T Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CaseStart_OfflineForm_OperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
            "/Schema.xsd2", Order=0)]
        public C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Request CaseStartOffline_Request;
        
        public CaseStart_OfflineForm_OperationRequest() {
        }
        
        public CaseStart_OfflineForm_OperationRequest(C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Request CaseStartOffline_Request) {
            this.CaseStartOffline_Request = CaseStartOffline_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CaseStart_OfflineForm_OperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/CaseStart_OfflineFormService/SharedResources/Schemas" +
            "/Schema.xsd2", Order=0)]
        public C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Response CaseStartOffline_Response;
        
        public CaseStart_OfflineForm_OperationResponse() {
        }
        
        public CaseStart_OfflineForm_OperationResponse(C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Response CaseStartOffline_Response) {
            this.CaseStartOffline_Response = CaseStartOffline_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortTypeChannel : C8.eServices.Mvc.CorrespondenceSoapService.PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortTypeClient : System.ServiceModel.ClientBase<C8.eServices.Mvc.CorrespondenceSoapService.PortType>, C8.eServices.Mvc.CorrespondenceSoapService.PortType {
        
        public PortTypeClient() {
        }
        
        public PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse C8.eServices.Mvc.CorrespondenceSoapService.PortType.CaseStart_OfflineForm_Operation(C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest request) {
            return base.Channel.CaseStart_OfflineForm_Operation(request);
        }
        
        public C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Response CaseStart_OfflineForm_Operation(C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Request CaseStartOffline_Request) {
            C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest inValue = new C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest();
            inValue.CaseStartOffline_Request = CaseStartOffline_Request;
            C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse retVal = ((C8.eServices.Mvc.CorrespondenceSoapService.PortType)(this)).CaseStart_OfflineForm_Operation(inValue);
            return retVal.CaseStartOffline_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse> C8.eServices.Mvc.CorrespondenceSoapService.PortType.CaseStart_OfflineForm_OperationAsync(C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest request) {
            return base.Channel.CaseStart_OfflineForm_OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationResponse> CaseStart_OfflineForm_OperationAsync(C8.eServices.Mvc.CorrespondenceSoapService.CaseStartOffline_Request CaseStartOffline_Request) {
            C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest inValue = new C8.eServices.Mvc.CorrespondenceSoapService.CaseStart_OfflineForm_OperationRequest();
            inValue.CaseStartOffline_Request = CaseStartOffline_Request;
            return ((C8.eServices.Mvc.CorrespondenceSoapService.PortType)(this)).CaseStart_OfflineForm_OperationAsync(inValue);
        }
    }
}
