//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.eServices.Mvc.DataAccessLayer.eBilling6Months
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillsArchive
    {
        public decimal Id { get; set; }
        public Nullable<decimal> QueueId { get; set; }
        public string Path { get; set; }
        public string Filename { get; set; }
        public Nullable<System.DateTime> ProcessedDateTime { get; set; }
    }
}
