//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.eServices.Mvc.DataAccessLayer.eBilling6Months
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueuePending
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> AccountNumber { get; set; }
        public string CustomerAccountName { get; set; }
        public string EmailSubject { get; set; }
        public string EmailAddressTo { get; set; }
        public string EmailAddressCc { get; set; }
        public Nullable<System.DateTime> QueueDateTime { get; set; }
        public Nullable<System.DateTime> ProcessedDateTime { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
